# Generated by Django 4.2.7 on 2025-10-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(help_text='Name of the source sheet', max_length=255)),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year for this summary')),
                ('total_records', models.IntegerField(help_text='Total number of budget records processed')),
                ('total_budget_amount', models.DecimalField(decimal_places=2, help_text='Total budget amount', max_digits=15)),
                ('max_budget_item', models.DecimalField(decimal_places=2, help_text='Maximum budget item amount', max_digits=15)),
                ('min_budget_item', models.DecimalField(decimal_places=2, help_text='Minimum budget item amount', max_digits=15)),
                ('average_budget_item', models.DecimalField(decimal_places=2, help_text='Average budget item amount', max_digits=15)),
                ('processing_date', models.DateTimeField(help_text='When this summary was generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Budget Summary',
                'verbose_name_plural': 'Budget Summaries',
                'ordering': ['-fiscal_year', '-processing_date'],
                'indexes': [models.Index(fields=['fiscal_year'], name='finance_bud_fiscal__759352_idx'), models.Index(fields=['processing_date'], name='finance_bud_process_fd43e6_idx')],
                'unique_together': {('sheet_name', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_source', models.CharField(help_text='Source of the budget data (Excel sheet, etc.)', max_length=255)),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year for this budget item')),
                ('processed_date', models.DateField(help_text='Date when this data was processed')),
                ('budget_category', models.CharField(help_text='Main budget category', max_length=255)),
                ('budget_item', models.CharField(help_text='Specific budget item', max_length=255)),
                ('budget_amount', models.DecimalField(decimal_places=2, help_text='Budget amount', max_digits=15)),
                ('budget_description', models.TextField(blank=True, help_text='Detailed description of the budget item')),
                ('department', models.CharField(blank=True, help_text='Department responsible for this budget', max_length=255)),
                ('account_code', models.CharField(blank=True, help_text='Internal account code', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Data',
                'verbose_name_plural': 'Budget Data',
                'ordering': ['-fiscal_year', 'budget_category', 'budget_item'],
                'indexes': [models.Index(fields=['fiscal_year'], name='finance_bud_fiscal__f40323_idx'), models.Index(fields=['budget_category'], name='finance_bud_budget__ac0804_idx'), models.Index(fields=['department'], name='finance_bud_departm_aee3eb_idx'), models.Index(fields=['processed_date'], name='finance_bud_process_a9d3d5_idx')],
            },
        ),
    ]
